apiVersion: las.installspec/v0.1.2
kind: InstallPlan

id: modelscope
category: tool

supported_platforms:
  - linux/amd64
  - linux/arm64

install_modes:
  - python

tools_required:
  - bash
  - python3
  - pip

description:
  purpose: Install the ModelScope SDK and CLI
  scope:
    - install
    - verify
    - uninstall
  non_goals:
    - configure authentication
    - manage system-wide Python versions

dependencies:
  system:
    - python3
    - python3-pip

preconditions:
  - id: P10
    intent: Python 3 available
    tool: shell
    command: command -v python3
    expected:
      exit_code: 0
  - id: P20
    intent: Pip available
    tool: shell
    command: python3 -m pip --version
    expected:
      exit_code: 0

decision_matrix:
  default: python

install:
  python:
    - id: S10
      intent: Install ModelScope via pip
      tool: shell
      command: python3 -m pip install --upgrade --user "modelscope"
      expected:
        exit_code: 0
      idempotent: true
    - id: S20
      intent: Verify CLI module entrypoint
      tool: shell
      command: >-
        python3 -c "import importlib.metadata as md; eps = md.entry_points();
        group = eps.select(group='console_scripts') if hasattr(eps, 'select') else
        eps.get('console_scripts', []); names = {ep.name for ep in group}; assert
        'modelscope' in names, f'Expected modelscope console script, found: {sorted(names)}'"
      expected:
        exit_code: 0
      idempotent: true

configuration:
  required: false
  defaults: {}
  templates: []

verification:
  script: scripts/verify.sh

rollback:
  script: scripts/uninstall.sh

uninstall:
  script: scripts/uninstall.sh

security:
  network:
    bind: localhost
    auth: token
  privileges:
    requires_sudo: false
